#!/usr/bin/env bash
set -euo pipefail

DATA_ROOT="${DATA_ROOT:-/data}"
MINIO_BACKEND="${MINIO_BACKEND:-${DATA_ROOT}/minio}"
MINIO_MOUNT="${MINIO_MOUNT:-/mnt/minio}"
POSTGRES_IMG="${POSTGRES_IMG:-${DATA_ROOT}/postgres.img}"
POSTGRES_MOUNT="${POSTGRES_MOUNT:-/mnt/postgres}"
POSTGRES_DATA="${POSTGRES_DATA:-${POSTGRES_MOUNT}/pgdata}"
POSTGRES_IMG_SIZE_GB="${POSTGRES_IMG_SIZE_GB:-8}"
FAKE_FREE_BYTES="${FAKE_FREE_BYTES:-10995116277760}" # 10 TiB

MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"
POSTGRES_USER="${POSTGRES_USER:-agent}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-agent}"
POSTGRES_DB="${POSTGRES_DB:-agent_constructor}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"

export FAKE_FREE_BYTES
export MINIO_ROOT_USER MINIO_ROOT_PASSWORD

echo "[entrypoint] DATA_ROOT=${DATA_ROOT}"
echo "[entrypoint] FAKE_FREE_BYTES=${FAKE_FREE_BYTES}"

mkdir -p "${MINIO_BACKEND}" "${MINIO_MOUNT}" "${POSTGRES_MOUNT}" /run/postgresql /var/log/supervisor
chmod 775 /run/postgresql || true

echo "[entrypoint] Raw df for ${DATA_ROOT}:"
df -h "${DATA_ROOT}" || true
df -i "${DATA_ROOT}" || true

# Detect broken free-space / inode reporting.
avail_kb="$(df -Pk "${DATA_ROOT}" | awk 'NR==2 {print $4}')"
inode_free="$(df -Pi "${DATA_ROOT}" | awk 'NR==2 {print $4}')"
need_fake=0
if [[ -z "${avail_kb}" || "${avail_kb}" -lt 524288 ]]; then
  need_fake=1
fi
# drvfs sometimes reports nonsense inode counts (negative / tiny).
if [[ -z "${inode_free}" || "${inode_free}" -lt 1000 ]]; then
  need_fake=1
fi

MINIO_DATA_PATH="${MINIO_BACKEND}"
if [[ "${need_fake}" -eq 1 ]]; then
  echo "[entrypoint] Broken free-space/inode stats detected — enabling fakefreespace"
  export LD_PRELOAD="/usr/local/lib/libfakefreespace.so${LD_PRELOAD:+:$LD_PRELOAD}"

  if mountpoint -q "${MINIO_MOUNT}"; then
    echo "[entrypoint] FUSE already mounted at ${MINIO_MOUNT}"
  else
    echo "[entrypoint] Mounting FUSE fakefreespace: ${MINIO_BACKEND} -> ${MINIO_MOUNT}"
    fakefreespace-mount "${MINIO_BACKEND}" "${MINIO_MOUNT}" "${FAKE_FREE_BYTES}" &
    fuse_pid=$!
    for _ in $(seq 1 50); do
      if mountpoint -q "${MINIO_MOUNT}"; then
        break
      fi
      if ! kill -0 "${fuse_pid}" 2>/dev/null; then
        echo "[entrypoint] ERROR: FUSE mount process exited early" >&2
        wait "${fuse_pid}" || true
        exit 1
      fi
      sleep 0.1
    done
    if ! mountpoint -q "${MINIO_MOUNT}"; then
      echo "[entrypoint] ERROR: FUSE mount did not become ready" >&2
      exit 1
    fi
  fi
  MINIO_DATA_PATH="${MINIO_MOUNT}"
  echo "[entrypoint] df after FUSE:"
  df -h "${MINIO_MOUNT}" || true
else
  echo "[entrypoint] Free space looks healthy — FUSE/LD_PRELOAD not required"
  export LD_PRELOAD="${LD_PRELOAD:-}"
fi

# --- PostgreSQL on ext4 loop image (SMB/drvfs cannot chmod for initdb) ---
ensure_postgres_image() {
  local size_gb="${POSTGRES_IMG_SIZE_GB}"
  if [[ ! -f "${POSTGRES_IMG}" ]]; then
    echo "[entrypoint] Creating ${POSTGRES_IMG} (${size_gb} GiB sparse)"
    # seek creates a sparse file that grows as Postgres writes.
    dd if=/dev/zero of="${POSTGRES_IMG}" bs=1M count=0 seek=$((size_gb * 1024))
    # lazy_* keeps first boot fast over SMB/drvfs.
    mkfs.ext4 -F -L pgdata -E lazy_itable_init=1,lazy_journal_init=1 "${POSTGRES_IMG}"
  fi
}

mount_postgres_image() {
  if mountpoint -q "${POSTGRES_MOUNT}"; then
    echo "[entrypoint] Postgres image already mounted at ${POSTGRES_MOUNT}"
    return 0
  fi
  ensure_postgres_image
  echo "[entrypoint] Mounting loop image ${POSTGRES_IMG} -> ${POSTGRES_MOUNT}"
  mount -o loop "${POSTGRES_IMG}" "${POSTGRES_MOUNT}"
  mkdir -p "${POSTGRES_DATA}"
  df -h "${POSTGRES_MOUNT}" || true
}

mount_postgres_image

PG_MAJOR="$(ls /usr/lib/postgresql | sort -V | tail -1)"
PG_BIN="/usr/lib/postgresql/${PG_MAJOR}/bin"
export PATH="${PG_BIN}:${PATH}"
export PGDATA="${POSTGRES_DATA}"

chown -R postgres:postgres "${POSTGRES_DATA}" /run/postgresql
chmod 700 "${POSTGRES_DATA}"

if [[ ! -f "${POSTGRES_DATA}/PG_VERSION" ]]; then
  echo "[entrypoint] Initializing PostgreSQL cluster in ${POSTGRES_DATA}"
  su -s /bin/bash postgres -c "env LD_PRELOAD='${LD_PRELOAD:-}' FAKE_FREE_BYTES='${FAKE_FREE_BYTES}' LANG=C LC_ALL=C ${PG_BIN}/initdb -D '${POSTGRES_DATA}' --encoding=UTF8 --no-locale"
  cat >> "${POSTGRES_DATA}/postgresql.conf" <<EOF

# Generated by entrypoint for container use
listen_addresses = '*'
port = ${POSTGRES_PORT}
lc_messages = 'C'
lc_monetary = 'C'
lc_numeric = 'C'
lc_time = 'C'
EOF
  cat > "${POSTGRES_DATA}/pg_hba.conf" <<EOF
# Generated by entrypoint — allow password auth from anywhere (LAN/dev).
local   all             all                                     trust
host    all             all             0.0.0.0/0               scram-sha-256
host    all             all             ::/0                    scram-sha-256
EOF
  chown postgres:postgres "${POSTGRES_DATA}/postgresql.conf" "${POSTGRES_DATA}/pg_hba.conf"
else
  sed -i -E "s/^[# ]*lc_(messages|monetary|numeric|time).*/lc_\\1 = 'C'/" "${POSTGRES_DATA}/postgresql.conf" || true
fi

bootstrap_sql() {
  local env_prefix="env LD_PRELOAD='${LD_PRELOAD:-}' FAKE_FREE_BYTES='${FAKE_FREE_BYTES}'"
  local sql_file="/tmp/pg_bootstrap.sql"
  cat > "${sql_file}" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
    CREATE ROLE ${POSTGRES_USER} LOGIN PASSWORD '${POSTGRES_PASSWORD}';
  ELSE
    ALTER ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
  END IF;
END
\$\$;
SQL
  su -s /bin/bash postgres -c "${env_prefix} ${PG_BIN}/pg_ctl -D '${POSTGRES_DATA}' -o \"-c listen_addresses='127.0.0.1' -p ${POSTGRES_PORT}\" -w start"
  su -s /bin/bash postgres -c "${env_prefix} ${PG_BIN}/psql -v ON_ERROR_STOP=1 -d postgres -f '${sql_file}'"
  local db_exists
  db_exists="$(su -s /bin/bash postgres -c "${env_prefix} ${PG_BIN}/psql -d postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='${POSTGRES_DB}'\"" | tr -d '[:space:]')"
  if [[ "${db_exists}" != "1" ]]; then
    su -s /bin/bash postgres -c "${env_prefix} ${PG_BIN}/psql -d postgres -c \"CREATE DATABASE ${POSTGRES_DB} OWNER ${POSTGRES_USER}\""
  fi
  su -s /bin/bash postgres -c "${env_prefix} ${PG_BIN}/pg_ctl -D '${POSTGRES_DATA}' -m fast -w stop"
  rm -f "${sql_file}"
}

if [[ ! -f "${POSTGRES_DATA}/.agent_bootstrapped" ]]; then
  echo "[entrypoint] Bootstrapping PostgreSQL role/database"
  bootstrap_sql
  touch "${POSTGRES_DATA}/.agent_bootstrapped"
  chown postgres:postgres "${POSTGRES_DATA}/.agent_bootstrapped"
fi

cat > /etc/supervisor/conf.d/runtime.env <<EOF
FAKE_FREE_BYTES=${FAKE_FREE_BYTES}
LD_PRELOAD=${LD_PRELOAD:-}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_DATA_PATH=${MINIO_DATA_PATH}
POSTGRES_DATA=${POSTGRES_DATA}
POSTGRES_PORT=${POSTGRES_PORT}
PG_BIN=${PG_BIN}
EOF

echo "[entrypoint] Starting supervisord (MinIO + PostgreSQL)"
exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
